simplexup: add new "commit" flag for specifying commit release

diff --git a/simplexup/simplexup b/simplexup/simplexup
--- a/simplexup/simplexup
+++ b/simplexup/simplexup
@@ -14,7 +14,8 @@ SIMPLEX_BIN_PATH="$SIMPLEX_BIN_DIR/simplexup"
 SIMPLEXUP_IGNORE_VERIFICATION=false
 DEFAULT_SIMPLEX_REPO="BlockstreamResearch/smplx"
 
-BINS=(simplex elementsd electrs)
+DEP_BINS=(elementsd electrs)
+BINS=(simplex "${DEP_BINS[@]}")
 HASH_NAMES=()
 HASH_VALUES=()
 
@@ -27,6 +28,7 @@ main() {
       --)               shift; break;;
 
       -v|--version)     shift; version;;
+      -C|--commit)      shift; SIMPLEX_COMMIT=$1;;
       -U|--update)      shift; update;;
       -r|--repo)        shift; SIMPLEX_REPO=$1;;
       -i|--install)     shift; SIMPLEX_VERSION=$1;;
@@ -72,16 +74,30 @@ main() {
   detect_platform_arch
 
   # Compute the URL of the release tarball in the Simplex repository.
-  RELEASE_URL="https://github.com/${SIMPLEX_REPO}/releases/download/${SIMPLEX_VERSION}/"
+  GITHUB_REPO_URL="https://github.com/${SIMPLEX_REPO}"
+  RELEASE_URL="${GITHUB_REPO_URL}/releases/download/${SIMPLEX_VERSION}/"
   ATTESTATION_URL="${RELEASE_URL}simplex-${SIMPLEX_VERSION}-${PLATFORM}-${ARCHITECTURE}.attestation.txt"
   BIN_ARCHIVE_URL="${RELEASE_URL}simplex-${SIMPLEX_VERSION}-${PLATFORM}-${ARCHITECTURE}.tar.gz"
 
-  ensure mkdir -p "$SIMPLEX_VERSIONS_DIR"
+  version_dir="${SIMPLEX_VERSIONS_DIR}/${SIMPLEX_VERSION}"
+  ensure mkdir -p "$version_dir"
+
+  local BINS_TO_DOWNLOAD=("${BINS[@]}")
+
+  if [[ -n "$SIMPLEX_COMMIT" ]]; then
+    local author="$(echo "${SIMPLEX_REPO}" | cut -d'/' -f1 -)"
+    BINS_TO_DOWNLOAD=("${DEP_BINS[@]}")
+
+    install_simplex_from_commit "${SIMPLEX_COMMIT}" "${author}" "${GITHUB_REPO_URL}" "${version_dir}"
+    say "Successfully compile simplex bin from commit: ${SIMPLEX_COMMIT} in repo: ${GITHUB_REPO_URL}"
+  fi
+
+  BINS_LIST_UX=$(form_str_list "${BINS_TO_DOWNLOAD[@]}")
 
   # If `--force` is set, skip the SHA verification.
   if [ "$SIMPLEXUP_IGNORE_VERIFICATION" = false ]; then
     # Check if the version is already installed by downloading the attestation file.
-    say "checking if simplex, elementsd and electrs for $SIMPLEX_VERSION version are already installed"
+    say "checking if $BINS_LIST_UX for $SIMPLEX_VERSION version are already installed"
 
     # Create a temporary directory to store the attestation link and artifact.
     tmp_dir="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
@@ -133,10 +149,9 @@ main() {
 
       # Check if the binaries are already installed and match the expected hashes.
       # If they do, skip the download.
-      version_dir="$SIMPLEX_VERSIONS_DIR/$SIMPLEX_VERSION"
       all_match=true
 
-      for bin in "${BINS[@]}"; do
+      for bin in "${BINS_TO_DOWNLOAD[@]}"; do
         expected=""
 
         for i in "${!HASH_NAMES[@]}"; do
@@ -162,7 +177,7 @@ main() {
       done
 
       if $all_match; then
-        say "version $SIMPLEX_VERSION already installed and verified, activating..."
+        say "version $SIMPLEX_VERSION already installed and verified (for $BINS_LIST_UX), activating..."
         use
         say "done!"
         exit 0
@@ -174,18 +189,21 @@ main() {
   fi
 
   # Download and extract the binaries archive
-  say "downloading simplex, elementsd and electrs for $SIMPLEX_VERSION version"
+  say "downloading $BINS_LIST_UX for $SIMPLEX_VERSION version"
 
-  tmp="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
-  tmp="$tmp/simplex.tar.gz"
+  tmp_dir="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
+  tmp_tar="$tmp_dir/simplex.tar.gz"
 
-  echo $BIN_ARCHIVE_URL
-  ensure download "$BIN_ARCHIVE_URL" "$tmp"
+  echo "$BIN_ARCHIVE_URL"
+  ensure download "$BIN_ARCHIVE_URL" "$tmp_tar"
   # Make sure it's a valid tar archive.
-  ensure tar tf "$tmp" 1> /dev/null
-  ensure mkdir -p "$SIMPLEX_VERSIONS_DIR/$SIMPLEX_VERSION"
-  ensure tar -C "$SIMPLEX_VERSIONS_DIR/$SIMPLEX_VERSION" -xvf "$tmp"
-  rm -f "$tmp"
+  ensure tar tf "$tmp_tar" 1> /dev/null
+  ensure tar -C "$tmp_dir" -xvf "$tmp_tar"
+
+  for bin in "${BINS_TO_DOWNLOAD[@]}"; do
+    mv "$tmp_dir/$bin" "$version_dir/$bin"
+  done
+  rm -rf "$tmp_dir"
 
   if [ "$SIMPLEXUP_IGNORE_VERIFICATION" = true ]; then
     say "skipped SHA verification for downloaded binaries due to --force flag"
@@ -199,7 +217,7 @@ main() {
 
       failed=false
 
-      for bin in "${BINS[@]}"; do
+      for bin in "${BINS_TO_DOWNLOAD[@]}"; do
         expected=""
 
         for i in "${!HASH_NAMES[@]}"; do
@@ -260,6 +278,7 @@ USAGE:
 OPTIONS:
     -h, --help      Print help information
     -v, --version   Print the version of simplexup
+    -C, --commit,   Install specific simplex revision from repository
     -U, --update    Update simplexup to the latest version
     -i, --install   Install a specific version from built binaries
     -l, --list      List versions installed from built binaries
@@ -348,6 +367,7 @@ use() {
     check_bins_in_use
 
     for bin in "${BINS[@]}"; do
+      ensure mkdir -p "$SIMPLEX_BIN_DIR"
       bin_path="$SIMPLEX_BIN_DIR/$bin"
       cp "$SIMPLEX_VERSION_DIR/$bin" "$bin_path"
       # Print usage msg
@@ -547,6 +567,48 @@ download() {
       wget --show-progress -qO- "$1"
     fi
   fi
+}
+
+# Form a comma separated list with 'and' for user experience
+form_str_list() {
+  local STR_LIST=("$@")
+
+  local LAST_EL="${STR_LIST[*]: -1}"
+  local REST_ELS=("${STR_LIST[@]:0:${#STR_LIST[@]}-1}")
+  local EL_STRING=""
+
+  if [ ${#STR_LIST[@]} -eq 1 ]; then
+    EL_STRING="${STR_LIST[0]}"
+  elif [ ${#STR_LIST[@]} -eq 2 ]; then
+    EL_STRING="${STR_LIST[0]} and ${STR_LIST[1]}"
+  else
+    SAVE_IFS="$IFS"
+    IFS=","
+    EL_STRING="${REST_ELS[*]}"
+    IFS="$SAVE_IFS"
+
+    EL_STRING="${EL_STRING//,/, } and ${LAST_EL}"
+  fi
+  echo "$EL_STRING"
+}
+
+install_simplex_from_commit() {
+  local commit=$1
+  local author=$2
+  local repo_url=$3
+  local out_dir=$4
+
+  local simplex_version="simplex-${author}-${commit}"
+  local tmp_dir="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
+  ensure git clone --revision="${commit}" --depth=1 "${repo_url}" "${tmp_dir}"
+
+  say "installing Simplex version $simplex_version"
+
+  ensure cargo build --release --manifest-path "${tmp_dir}/Cargo.toml"
+  ensure mv "${tmp_dir}/target/release/simplex" "${out_dir}/simplex"
+
+  say "Removing temporary directory..."
+  rm -rf "${tmp_dir}"
 }
 
 validate_tag_version() {
