update simplexup

diff --git a/simplexup/simplexup b/simplexup/simplexup
--- a/simplexup/simplexup
+++ b/simplexup/simplexup
@@ -3,7 +3,7 @@ set -eo pipefail
 
 # NOTE: if you make modifications to this script, please increment the version number.
 # WARNING: the SemVer pattern: major.minor.patch must be followed as we use it to determine if the script is up to date.
-SIMPLEXUP_INSTALLER_VERSION="2.0.25"
+SIMPLEXUP_INSTALLER_VERSION="0.0.1"
 
 BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
 SIMPLEX_DIR=${SIMPLEX_DIR:-"$BASE_DIR/.simplex"}
@@ -14,7 +14,7 @@ SIMPLEX_BIN_PATH="$SIMPLEX_BIN_DIR/simplexup"
 SIMPLEXUP_IGNORE_VERIFICATION=false
 DEFAULT_SIMPLEX_REPO="BlockstreamResearch/smplx"
 
-BINS=(test3-crate-ikripaka elementsd electrs)
+BINS=(simplex elementsd electrs)
 HASH_NAMES=()
 HASH_VALUES=()
 
@@ -59,9 +59,7 @@ main() {
   # Default to Simplex repo
   SIMPLEXUP_REPO=${SIMPLEXUP_REPO:-$DEFAULT_SIMPLEX_REPO}
 
-
   # Install by downloading binaries
-  # TODO: add stable version to releases `SIMPLEXUP_VERSION=${SIMPLEXUP_VERSION:-stable}`
   SIMPLEXUP_VERSION=${SIMPLEXUP_VERSION:-$SIMPLEXUP_INSTALLER_VERSION}
   SIMPLEXUP_TAG=$SIMPLEXUP_VERSION
 
@@ -76,8 +74,8 @@ main() {
 
   # Compute the URL of the release tarball in the Simplex repository.
   RELEASE_URL="https://github.com/${SIMPLEXUP_REPO}/releases/download/${SIMPLEXUP_TAG}/"
-  ATTESTATION_URL="${RELEASE_URL}simple_${SIMPLEXUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.attestation.txt"
-  BIN_ARCHIVE_URL="${RELEASE_URL}simple_${SIMPLEXUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.$EXT"
+  ATTESTATION_URL="${RELEASE_URL}simplex_${SIMPLEXUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.attestation.txt"
+  BIN_ARCHIVE_URL="${RELEASE_URL}simplex_${SIMPLEXUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.tar.gz"
 
   ensure mkdir -p "$SIMPLEX_VERSIONS_DIR"
 
@@ -110,7 +108,6 @@ main() {
     else
       say "found attestation for $SIMPLEXUP_TAG version, downloading attestation artifact, checking..."
 
-
       # Download the attestation artifact JSON file.
       tmp="$tmp_dir/simplex-attestation.sigstore.json"
       ensure download "${attestation_artifact_link}/download" "$tmp"
@@ -118,7 +115,6 @@ main() {
       # Extract the payload from the JSON file.
       payload_b64=$(awk '/"payload":/ {gsub(/[",]/, "", $2); print $2; exit}' "$tmp")
       payload_json=$(printf '%s' "$payload_b64" | base64 -d 2>/dev/null || printf '%s' "$payload_b64" | base64 -D)
-
 
       # Extract the names and hashes from the payload JSON.
       # The payload is expected to be a JSON array of objects with "name" and "sha256" fields.
@@ -139,6 +135,7 @@ main() {
       # If they do, skip the download.
       version_dir="$SIMPLEX_VERSIONS_DIR/$SIMPLEXUP_TAG"
       all_match=true
+
       for bin in "${BINS[@]}"; do
         expected=""
         for i in "${!HASH_NAMES[@]}"; do
@@ -177,23 +174,16 @@ main() {
 
   # Download and extract the binaries archive
   say "downloading simplex, elementsd and electrs for $SIMPLEXUP_TAG version"
-  if [ "$PLATFORM" = "win32" ]; then
-    tmp="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
-    tmp="$tmp/simplex.zip"
-    ensure download "$BIN_ARCHIVE_URL" "$tmp"
-    ensure unzip "$tmp" -d "$SIMPLEX_VERSIONS_DIR/$SIMPLEXUP_TAG"
-    rm -f "$tmp"
-  else
-    tmp="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
-    tmp="$tmp/simplex.tar.gz"
-    echo $BIN_ARCHIVE_URL
-    ensure download "$BIN_ARCHIVE_URL" "$tmp"
-    # Make sure it's a valid tar archive.
-    ensure tar tf "$tmp" 1> /dev/null
-    ensure mkdir -p "$SIMPLEX_VERSIONS_DIR/$SIMPLEXUP_TAG"
-    ensure tar -C "$SIMPLEX_VERSIONS_DIR/$SIMPLEXUP_TAG" -xvf "$tmp"
-    rm -f "$tmp"
-  fi
+
+  tmp="$(mktemp -d 2>/dev/null)" || err "failed to create temp dir"
+  tmp="$tmp/simplex.tar.gz"
+  echo $BIN_ARCHIVE_URL
+  ensure download "$BIN_ARCHIVE_URL" "$tmp"
+  # Make sure it's a valid tar archive.
+  ensure tar tf "$tmp" 1> /dev/null
+  ensure mkdir -p "$SIMPLEX_VERSIONS_DIR/$SIMPLEXUP_TAG"
+  ensure tar -C "$SIMPLEX_VERSIONS_DIR/$SIMPLEXUP_TAG" -xvf "$tmp"
+  rm -f "$tmp"
 
   if [ "$SIMPLEXUP_IGNORE_VERIFICATION" = true ]; then
     say "skipped SHA verification for downloaded binaries due to --force flag"
@@ -257,7 +247,7 @@ usage() {
   cat 1>&2 <<EOF
 The installer for Simplex.
 
-Update or revert to a specific Simplex version with ease.
+Install, update, and manage Simplex with ease.
 
 By default, the latest stable version is installed from built binaries.
 
@@ -410,15 +400,10 @@ check_cmd() {
 detect_platform_arch() {
   uname_s=$(uname -s)
   PLATFORM=$(tolower "${SIMPLEXUP_PLATFORM:-$uname_s}")
-  EXT="tar.gz"
   case $PLATFORM in
-    linux|alpine) ;;
+    linux) ;;
     darwin|mac*)
       PLATFORM="darwin"
-      ;;
-    mingw*|win*)
-      EXT="zip"
-      PLATFORM="win32"
       ;;
     *)
       err "unsupported platform: $PLATFORM"
@@ -434,7 +419,7 @@ detect_platform_arch() {
     else
       ARCHITECTURE="amd64" # Intel.
     fi
-  elif [ "${ARCHITECTURE}" = "arm64" ] ||[ "${ARCHITECTURE}" = "aarch64" ] ; then
+  elif [ "${ARCHITECTURE}" = "arm64" ] || [ "${ARCHITECTURE}" = "aarch64" ] ; then
     ARCHITECTURE="arm64" # Arm.
   else
     ARCHITECTURE="amd64" # Amd.
@@ -545,22 +530,27 @@ download() {
 banner() {
   printf '
 
--~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
-      /\          ▗▄▄▖▗▄▄▄▖▗▖  ▗▖▗▄▄▖ ▗▖   ▗▄▄▄▖▗▖  ▗▖
-     /  \        ▐▌     █  ▐▛▚▞▜▌▐▌ ▐▌▐▌   ▐▌    ▝▚▞▘
-    /|   \        ▝▀▚▖  █  ▐▌  ▐▌▐▛▀▘ ▐▌   ▐▛▀▀▘  ▐▌
-   / |    \      ▗▄▄▞▘▗▄█▄▖▐▌  ▐▌▐▌   ▐▙▄▄▖▐▙▄▄▖▗▞▘▝▚▖
-  /  |     \       A blazingly-fast, ux-first simplicity framework.
- /___|______\        Rust SDK | Zero-Config | Liquid | Local Regtest
--~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
+-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
+                       _.|
+                  _ -../ | 
+              _ -..::/ ||          ____  _                 _         
+          _ -..:::::/ |||         / ___|(_)_ __ ___  _ __ | | _____  __
+     _ .....:.:.:. / ||||         \___ \| | '_ ` _ \| '_ \| |/ _ \ \/ /
+  -- -- _ .:.:... /  |||           ___) | | | | | | | |_) | |  __/>  <
+      -- ... -- _/  ||||          |____/|_|_| |_| |_| .__/|_|\___/_/\_\
+          _ :_:..\ |||||                            |_|
+             _ :..\ |||
+                _ .\ ||      A blazingly-fast, ux-first simplicity framework.
+                  - \ | 
+                    -.
+-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
 
-Repo       : https://github.com/BlockstreamResearch/simplex
-Contribute : https://github.com/BlockstreamResearch/simplex/blob/HEAD/CONTRIBUTING.md
+Repo       : https://github.com/BlockstreamResearch/smplx
+Contribute : https://github.com/BlockstreamResearch/smplx/blob/master/CONTRIBUTING.md
 
--~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
+-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
 
 '
 }
-
 
 main "$@"
